# Generated by Django 3.2.9 on 2021-12-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('pending', 'pending'), ('approved', 'approved'), ('completed', 'completed')], default='booked', max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prefix',
            field=models.CharField(choices=[('Dr', 'Doctor'), ('PTA', 'Pediatrician'), ('PSo', 'Psycologist'), ('Gdr', 'generalist')], default=None, max_length=15),
        ),
    ]
