# Generated by Django 3.2.9 on 2021-12-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0003_doctor_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoitment',
            name='appoitment_id',
        ),
    ]
