# Generated by Django 3.2.9 on 2021-12-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0005_rename_hospital_doctor_hospital_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='hospital_id',
            new_name='hospital',
        ),
    ]
