# Generated by Django 3.2.9 on 2021-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0006_rename_hospital_id_doctor_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='doctor_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appoitment',
            name='lab_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appoitment',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
