# Generated by Django 3.2.9 on 2021-12-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0008_alter_appoitment_appoitment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appApi.doctor'),
        ),
        migrations.AlterField(
            model_name='appoitment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appApi.patient'),
        ),
    ]
