# Generated by Django 3.2.9 on 2021-12-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0011_alter_hospital_accepted_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='province',
            field=models.CharField(choices=[('North', 'North'), ('East', 'East'), ('West', 'West'), ('South', 'South')], default=None, max_length=55),
        ),
    ]
