# Generated by Django 3.2.9 on 2021-12-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0012_alter_hospital_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='accepted_insurance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appApi.insurance'),
        ),
    ]
