# Generated by Django 3.2.9 on 2021-12-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0014_auto_20211202_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
    ]
