# Generated by Django 3.2.9 on 2021-12-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0004_remove_appoitment_appoitment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='hospital',
            new_name='hospital_id',
        ),
    ]
