# Generated by Django 3.2.9 on 2021-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0007_auto_20211202_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='appoitment_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
